### ISSUE TITLE
README needed

### ISSUE THREAD

**Issue by nicola** [satwantrana/CharSCNN#1]
It would be great to have a Readme on how to use this code, probably people will have the incentive of building on top!

**Comment by satwantrana** [comment]
I'll get back to you soon.

**Comment by satwantrana** [comment]
Hi Nicola,

I was a little busy with some exams, so couldn't reply back then.

The code is very messy, which I never cared to organise. The version that
works is "con.py" is a modification of convolutional neural network code
available on theano's website.

The dimensions are smaller, and the network gives 70% precision on a
sarcastic tweets + normal tweets. I'll organise the code soon, and will let
you know.

Thanks

**Comment by satwantrana** [comment]
I had mistakenly uploaded an old, dysfunctional version of the code. The current version is better, though not ideal. There is a readme as well.
