### ISSUE TITLE
Run error in cnn.py

### ISSUE THREAD

**Issue by berlino** [satwantrana/CharSCNN#2]
In line 121 of cnn.py
cemb = T.stack(temp[i] for i in xrange(len(temp)))

theano.tensor.var.AsTensorError: ('Cannot convert <generator object <genexpr> at 0xa9c26f2c> to TensorType', <type 'generator'>)

**Comment by satwantrana** [comment]
I had mistakenly uploaded an old, dysfunctional version of the code. The current version is better, though not ideal. There is a readme as well.
